version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    command: python src/main.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9100:9100"